---

global:
  scrape_interval: 30s

scrape_configs:
- job_name: jmx
  static_configs:
  - targets: ["mbean_exporter:1234"]

remote_write:
- name: kafka
  url: "http://prometheus-writer:9089/receive"
  write_relabel_configs:
    # Drop internal topics
  - source_labels: [topic]
    regex: (^_.+|prometheus-.+|kafka-.+)
    action: drop

    # Drop internal/unknown users
  - source_labels: [user]
    regex: (statefun|ANONYMOUS)
    action: drop

    # For our example, topics are single-partition
  - regex: partition
    action: labeldrop

    # Mark topic metrics to keep
  - source_labels: [__name__]
    regex: (kafka_topic_messages_in_rate|kafka_topic_bytes_in_rate|kafka_topic_bytes_out_rate|kafka_topic_log_size)
    target_label: __continue
    # Mark topic metrics to keep

    # Mark user/quota metrics to keep
  - source_labels: [__name__]
    regex: (kafka_user_produce_byte_rate|kafka_user_fetch_byte_rate)
    target_label: __continue

    # Keep all metrics with a __continue label
  - source_labels: [__continue]
    regex: .+
    action: keep

    # Drop extraneous labels
  - regex: __continue|job|instance
    action: labeldrop
